---
- name: Install kvm and dependencies
  dnf:
    name:
      - qemu-kvm
      - guestfs-tools
      - python3-libvirt
    state: latest
  become: true

- name: Download VM Image
  get_url: "{{ vm_image_url }}"
  dest: "{{ libvirt_pool_dir }}{{ vm_image_name }}"
  checksum: "sha256:{{ vm_image_checksum }}"